Add SingleOffer page
shareio-pl/shareio-frontend pull request #34
Opened 2024-05-07 00:29 UTC by Bicik89

OfferPreview plik wziąłem już z tej wersji, gdzie miały być po dwa w wierszu (ze wzgl. na guzik), ale że jeszcze to nie jest do końca ustalone, to na ten moment są w jednej kolumnie

2024-05-07 09:46 UTC, 242370 requested changes

2024-05-07 09:46 UTC, 242370 commented on src/components/organisms/OfferPreview.vue
> +      window.location.href = `/offer/get/${this.id}`;
Change to router.push like in Header

2024-05-07 09:46 UTC, 242370 commented on src/router.js
> +    path: "/offer/get/:id",
change to offer/:id

2024-05-07 09:46 UTC, 242370 commented on src/components/pages/SingleOffer.vue
> +      <OfferPreview v-for="id in ownerOffers" :key="id" :id=id :is-new="true"/>
remove :is-new prop

2024-05-07 09:46 UTC, 242370 commented on src/components/pages/SingleOffer.vue
> +      COLORS: COLORS,
Move consts to the top of return

2024-05-07 09:46 UTC, 242370 commented on src/components/pages/SingleOffer.vue
> +    axios.get(GATEWAY_ADDRESS + '/debug/getOfferIds').then((response) => {
Add TODO: change to getOffersByUserId endpoint

2024-05-10 17:51 UTC, Piotr-Skrobski commented
1) Use this.$router.push('/map') in your navigateToOfferPage

2024-05-13 17:37 UTC, 242370 approved these changes

2024-05-13 17:37 UTC, merged