Add Button primary
shareio-pl/shareio-frontend pull request #4
Opened 2024-03-31 15:46 UTC by Piotr-Skrobski

2024-04-02 15:16 UTC, Piotr-Skrobski commented
1) changed the name of atom
2) removed unnecessary emit

2024-04-03 12:40 UTC, 242370 requested changes

2024-04-03 12:40 UTC, 242370 commented on src/components/atoms/PrimaryButton.vue
> +  <button class="button-primary">
Change file name to ButtonPrimary.vue

2024-04-04 14:45 UTC, 242370 approved these changes

2024-04-04 14:45 UTC, merged