Add search input atom
shareio-pl/shareio-frontend pull request #7
Opened 2024-04-03 15:43 UTC by Piotr-Skrobski

2024-04-04 16:26 UTC, 242370 requested changes

2024-04-04 16:26 UTC, 242370 commented on src/components/atoms/SearchInput.vue
> +    dropdownIcon: {
Remove from props

2024-04-06 20:47 UTC, Piotr-Skrobski reviewed
I tested if the emission of the event will work; it did. I don't think there's much to comment on this one.

2024-04-06 21:51 UTC, 242370 approved these changes

2024-04-06 21:52 UTC, merged