Add_Menu
shareio-pl/shareio-frontend pull request #77
Opened 2024-05-28 21:15 UTC by Piotr-Skrobski

2024-05-28 21:17 UTC, Piotr-Skrobski commented
Code issues are TODOs, which is understandable; but the multiple imports I don't see.

2024-05-29 06:59 UTC, 242370 requested changes
This component is only accessible when user is logged in (there is alternative header on Figma if that condition is false) so it should always look the same (therefore remove "Zaloguj się", it should always be "Wyloguj się") and "Moje konto" should always be visible. Morevoer the text should be placed the same horizontally as name and surname.

2024-05-29 07:46 UTC, 242370 requested changes
On the texts in menu add underline on hover and make the menu appear on the entire "user-data" div click

2024-05-29 09:15 UTC, 242370 approved these changes

2024-05-29 09:15 UTC, merged