Add Category atom
shareio-pl/shareio-frontend pull request #8
Opened 2024-04-03 18:16 UTC by Piotr-Skrobski

2024-04-04 16:37 UTC, 242370 requested changes

2024-04-04 16:37 UTC, 242370 commented on src/components/atoms/Category.vue
> +<style scoped>
Add PRIMARY font size and TEXT_SECONDARY font colour

2024-04-04 16:37 UTC, 242370 commented on src/components/atoms/Category.vue
> +</style>
Add hover cursor and hover font colour to new font TEXT_HOVER

2024-04-16 10:17 UTC, Caranthi approved these changes

2024-04-16 10:17 UTC, Caranthi approved these changes

2024-04-16 10:19 UTC, 242370 approved these changes

2024-04-16 10:19 UTC, merged